서블릿은 2가지 방식으로 예외 처리를 지원한다.
1. Exception (예외)
2. response.sendError(Http 상태 코드, 오류 메시지)

"자바 직접 실행"
자바의 메인 메서드를 직접 실행하는 경우 main 이라는 이름의 쓰레드가 실행된다.
실행 도중에 예외를 잡지 못하고 실행한 main() 메서드를 넘어서 예외가 던져지면, 예외 정보를 넘기고 해당 쓰레드는 종료된다.

"웹 애플리케이션"
웹 애플리케이션은 사용자 요청별로 별도의 쓰레드가 할당되고, 서블릿 컨테이너 안에서 실행된다.
애플리케이션에서 예외가 발생했는데, 어디선가 try ~ catch로 예외를 잡아서 처리하면 아무 문제가 없다.
그런데 만약에 애플리케이션에서 예외를 잡지 못하고, 서블릿 밖으로 까지 예외가 전달되면 어떻게 동작할까?

결국 톰캣 같은 WAS 까지 예외가 전달된다.
WAS는 예외가 올라오면 어떻게 처리해야할까?

Exception의 경우 서버 내부에서 처리할 수 없는 오류가 발생한 것으로 생각해서 HTTP 상태 코드 500을 반환한다.